# roles/squid/handlers/main.yml
---

- name: Restart Squid
  systemd:
    name: "{{ squid_service }}"
    daemon_reload: yes
    state: restarted
  become: yes

- name: Reload Squid
  systemd:
    name: "{{ squid_service }}"
    daemon_reload: yes
    state: reloaded
  become: yes
